### ISSUE TITLE
deepin 15.5 not supported

### ISSUE THREAD

**Issue by sikenali** [GabMus/HydraPaper#14]
![_ _20180202141127](https://user-images.githubusercontent.com/26103116/35719379-39c1bd04-0824-11e8-9d70-68830147b1ac.png)

**Comment by GabMus** [comment]
Send output of `cat ~/.config/monitors.xml`.

If not found, try messing around with your monitor settings and try again with the command above.

Mind that this app is written for GNOME, and at this point it doesn't officially support Deepin or any other DE. This is because the wallpaper is set using gsettings on GNOME specific keys.

**Comment by sikenali** [comment]
No found ~/.config/monitors.xml file

**Comment by GabMus** [comment]
As I said, I have no plan in supporting deepin myself. I think this issue will remain open for quite a while.

**Comment by sikenali** [comment]
tks

**Comment by GabMus** [comment]
Hey @jingle0927 you should try [this new flatpak](https://github.com/GabMus/HydraPaper/files/1724065/hydrapaper-1.1.3-82-gc8917d1.zip).

Along with a design change, I also dropped monitors.xml in favor of straight Gdk, this could make HydraPaper work on deepin, I think it's worth a try.

**Comment by sikenali** [comment]
Thanks
